site_name: OG Amsterdam APV
site_url: https://ogamsterdam.github.io/apv/

theme:
  name: material
  language: nl

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - APV: apv.md
  - Onderwereld: onderwereld.md
  - Wetboek:
      - Overzicht: wetboek/index.md
      - Algemene bepalingen: wetboek/algemene-bepalingen.md
      - Vermogensdelicten: wetboek/vermogensdelicten.md
      - Geweldsdelicten: wetboek/geweldsdelicten.md
      - Verkeersdelicten: wetboek/verkeersdelicten.md
      - Opiumwet: wetboek/opiumwet.md
      - Wet wapens en munitie: wetboek/wet-wapens-en-munitie.md
      - Overige: wetboek/overige.md
