site_name: OG Amsterdam APV
site_url: https://ogamsterdam.github.io/apv/

theme:
  name: material
  language: nl

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - APV: apv.md
  - Onderwereld: onderwereld.md
